In [18]:
import warnings
import numpy as np
import pandas as pd
warnings.filterwarnings('ignore')

In [19]:
url = 'https://drive.google.com/file/d/19E-Sh2TomdKqIpyWXLM3FZMQnheP0dCm/view?usp=sharing'
url = 'https://drive.google.com/uc?id=' + url.split('/')[-2]
movies = pd.read_csv(url)
movies.head(10)

id                        title                     genre  \
0     278     The Shawshank Redemption               Drama,Crime   
1   19404  Dilwale Dulhania Le Jayenge      Comedy,Drama,Romance   
2     238                The Godfather               Drama,Crime   
3     424             Schindler's List         Drama,History,War   
4     240       The Godfather: Part II               Drama,Crime   
5  667257            Impossible Things              Family,Drama   
6     129                Spirited Away  Animation,Family,Fantasy   
7  730154               Your Eyes Tell             Romance,Drama   
8  372754     Dou kyu sei – Classmates         Romance,Animation   
9  372058                   Your Name.   Romance,Animation,Drama   

  original_language                                           overview  \
0                en  Framed in the 1940s for the double murder of h...   
1                hi  Raj is a rich, carefree, happy-go-lucky second...   
2                en  Spanning the years 1945 to 1955, a chronicle o...   
3                en  The true story of how businessman Oskar Schind...   
4                en  In the continuing saga of the Corleone crime f...   
5                es  Matilde is a woman who, after the death of her...   
6                ja  A young girl, Chihiro, becomes trapped in a st...   
7                ja  A tragic accident lead to Kaori's blindness, b...   
8                ja  Rihito Sajo, an honor student with a perfect s...   
9                ja  High schoolers Mitsuha and Taki are complete s...   

   popularity release_date  vote_average vote_count  
0      94.075    9/23/1994           8.7     21862a  
1      25.408   10/19/1995           8.7       3731  
2      90.585    3/14/1972           8.7      16280  
3      44.761   12/15/1993           8.6      12959  
4      57.749   12/20/1974           8.6       9811  
5      14.358    6/17/2021           8.6        255  
6      92.056    7/20/2001           8.5      13093  
7      51.345   10/23/2020           8.5        339  
8      14.285    2/20/2016           8.5        239  
9     158.270    8/26/2016           8.5       8895

In [20]:
selected_features = ['overview', 'genre']
print(selected_features)

['overview', 'genre']


In [21]:
for feature in selected_features:
  movies[feature] = movies[feature].fillna('')

In [22]:
movies=movies[['id', 'title', 'overview', 'genre']]

In [23]:
movies['tags'] = movies['overview']+movies['genre']
movies

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                               overview  \
0     Framed in the 1940s for the double murder of h...   
1     Raj is a rich, carefree, happy-go-lucky second...   
2     Spanning the years 1945 to 1955, a chronicle o...   
3     The true story of how businessman Oskar Schind...   
4     In the continuing saga of the Corleone crime f...   
...                                                 ...   
9995  The story follows the adventures of Aang, a yo...   
9996  The sharks take bite out of the East Coast whe...   
9997  During World War II, a brave, patriotic Americ...   
9998  A man named Farmer sets out to rescue his kidn...   
9999  Seeking justice for his partner’s murder by an...   

                                                 genre  \
0                                          Drama,Crime   
1                                 Comedy,Drama,Romance   
2                                          Drama,Crime   
3                                    Drama,History,War   
4                                          Drama,Crime   
...                                                ...   
9995                          Action,Adventure,Fantasy   
9996  Action,TV Movie,Science Fiction,Comedy,Adventure   
9997                        Action,Science Fiction,War   
9998                    Adventure,Fantasy,Action,Drama   
9999                             Thriller,Action,Crime   

                                                   tags  
0     Framed in the 1940s for the double murder of h...  
1     Raj is a rich, carefree, happy-go-lucky second...  
2     Spanning the years 1945 to 1955, a chronicle o...  
3     The true story of how businessman Oskar Schind...  
4     In the continuing saga of the Corleone crime f...  
...                                                 ...  
9995  The story follows the adventures of Aang, a yo...  
9996  The sharks take bite out of the East Coast whe...  
9997  During World War II, a brave, patriotic Americ...  
9998  A man named Farmer sets out to rescue his kidn...  
9999  Seeking justice for his partner’s murder by an...  

[10000 rows x 5 columns]

In [24]:
combined_features= movies['tags']

In [25]:
new_data  = movies.drop(columns=['overview', 'genre'])
new_data

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                   tags  
0     Framed in the 1940s for the double murder of h...  
1     Raj is a rich, carefree, happy-go-lucky second...  
2     Spanning the years 1945 to 1955, a chronicle o...  
3     The true story of how businessman Oskar Schind...  
4     In the continuing saga of the Corleone crime f...  
...                                                 ...  
9995  The story follows the adventures of Aang, a yo...  
9996  The sharks take bite out of the East Coast whe...  
9997  During World War II, a brave, patriotic Americ...  
9998  A man named Farmer sets out to rescue his kidn...  
9999  Seeking justice for his partner’s murder by an...  

[10000 rows x 3 columns]

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

  (0, 6050)	0.0612538429167934
  (0, 7748)	0.03828766689752139
  (0, 12100)	0.11799536206639417
  (0, 22496)	0.1330115400559194
  (0, 26579)	0.19480620340355656
  (0, 13053)	0.17383657784387052
  (0, 20630)	0.13111831391223913
  (0, 17086)	0.09444231478678394
  (0, 19690)	0.14487708742766808
  (0, 17838)	0.1213893210729216
  (0, 12709)	0.11648113744709981
  (0, 12931)	0.1618722797825502
  (0, 18067)	0.08679724224466641
  (0, 3839)	0.05270978856697799
  (0, 711)	0.17998707276541237
  (0, 2526)	0.06983295254939055
  (0, 5210)	0.09828817440902823
  (0, 24274)	0.16516794212726824
  (0, 15027)	0.09892168701946276
  (0, 7959)	0.08730465408531558
  (0, 27351)	0.1634566701565928
  (0, 1229)	0.18388501398779
  (0, 1255)	0.09376201216899409
  (0, 27901)	0.0974466548699561
  (0, 25562)	0.05471221694153387
  :	:
  (9999, 14051)	0.13854867540933413
  (9999, 11894)	0.11618216034196392
  (9999, 22410)	0.17885319647240247
  (9999, 10354)	0.14697971230095458
  (9999, 17798)	0.153239729765301
  (9999, 1

In [27]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.06362268 0.06544422 ... 0.07336891 0.0808491  0.06708015]
 [0.06362268 1.         0.04012619 ... 0.03013573 0.03153386 0.02911721]
 [0.06544422 0.04012619 1.         ... 0.03562469 0.05258387 0.03343605]
 ...
 [0.07336891 0.03013573 0.03562469 ... 1.         0.03274969 0.01643958]
 [0.0808491  0.03153386 0.05258387 ... 0.03274969 1.         0.0392191 ]
 [0.06708015 0.02911721 0.03343605 ... 0.01643958 0.0392191  1.        ]]


In [28]:
print(similarity.shape)

(10000, 10000)


In [29]:
movie_name = input(' Enter your favourite movie name : ')

In [30]:
import difflib
if 'index' not in movies.columns:
    movies.reset_index(inplace=True)
list_of_all_titles = movies['title'].tolist()
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
close_match = find_close_match[0]
index_of_the_movie = movies[movies.title == close_match]['index'].values[0]
similarity_score = list(enumerate(similarity[index_of_the_movie]))
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print('Movies suggested for you : \n')
i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies[movies.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Avatar
2 . Apollo 18
3 . The Matrix
4 . Europa Report
5 . Mune: Guardian of the Moon
6 . Tears of the Sun
7 . The American
8 . Hellraiser: Bloodline
9 . Prospect
10 . Stand by Me Doraemon
11 . Spectral
12 . The Book of Life
13 . Bitter Moon
14 . Blood and Chocolate
15 . Skylines
16 . I Am Mother
17 . Thor: Ragnarok
18 . E.T. the Extra-Terrestrial
19 . Aliens vs Predator: Requiem
20 . Predator 2
21 . Azumi
22 . Supernova
23 . Captain Marvel
24 . Star Trek IV: The Voyage Home
25 . First Man
26 . Rakka
27 . Moonfall
28 . Krull
29 . Iron Man 3


In [31]:
import pickle

In [32]:
pickle.dump(new_data, open('movies_list.pkl', 'wb'))

In [33]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [34]:
pickle.load(open('movies_list.pkl', 'rb'))

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                   tags  
0     Framed in the 1940s for the double murder of h...  
1     Raj is a rich, carefree, happy-go-lucky second...  
2     Spanning the years 1945 to 1955, a chronicle o...  
3     The true story of how businessman Oskar Schind...  
4     In the continuing saga of the Corleone crime f...  
...                                                 ...  
9995  The story follows the adventures of Aang, a yo...  
9996  The sharks take bite out of the East Coast whe...  
9997  During World War II, a brave, patriotic Americ...  
9998  A man named Farmer sets out to rescue his kidn...  
9999  Seeking justice for his partner’s murder by an...  

[10000 rows x 3 columns]